---
title: "HW2"
author: "Amin Yakubu"
date: "3/16/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(caret)
library(tidyverse)
library(gam)
```

Let's read in the data 

```{r}
concrete_df = read_csv('data/concrete.csv')
attach(concrete_df)
```

```{r}
X = model.matrix(CompressiveStrength ~ ., concrete_df)[,-1]
y = concrete_df$CompressiveStrength
```

## Scatter plots

```{r}
theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.3, .5, .2, .5)
theme1$plot.symbol$pch <- 18
theme1$plot.line$col <- rgb(.8, .1, .1, 1)
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)
featurePlot(X, y, plot = "scatter", labels = c("","Y"),
            type = c("p"), layout = c(4, 2))
```

```{r}
fit1 = lm(CompressiveStrength ~ Water, data = concrete_df)
fit2 = lm(CompressiveStrength ~ poly(Water, 2), data = concrete_df)
fit3 = lm(CompressiveStrength ~ poly(Water, 3), data = concrete_df)
fit4 = lm(CompressiveStrength ~ poly(Water, 4), data = concrete_df)
```

```{r}
anova(fit1, fit2, fit3, fit4)
```


Question 2

```{r}
fit.ss.cv <- smooth.spline(concrete_df$Water, concrete_df$CompressiveStrength, cv = TRUE)
fit.ss.cv$df

fit.ss <- smooth.spline(concrete_df$Water, concrete_df$CompressiveStrength)
fit.ss$df
```

```{r}
water_lims <- range(concrete_df$Water)
water.grid <- seq(from = water_lims[1], to = water_lims[2])
```


```{r}
gam.m1 <- gam(CompressiveStrength ~ . + s(Water), data = concrete_df)
plot(gam.m1)
```














































